# Site
name: 'IUST Projects'
description: 'Projects by Students of Iran University of Science and Technology'
logo: 'assets/images/iust.png'
favicon: 'assets/images/favicon.png'
baseurl: ''
disqus: ''
email: 'Oxaryan@outlook.com'
mailchimp-list: 'https://iust-projects.us4.list-manage.com/subscribe/post?u=ea24c7aae0b3e77b165456303&amp;id=0a42a113bf'

include: ["_pages"]
permalink: /:title/

collections:
  member:
    output: true
    permalink: /member/:path

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

  # all member pages
  - scope:
      path: "member"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]